debugging...

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -54,11 +54,11 @@ jobs:
       matrix:
         node:
           - 20.x
-          - 22.x
+          #- 22.x
         platform:
           - os: ubuntu-latest
-          - os: macos-latest
-          - os: windows-latest
+          #- os: macos-latest
+          #- os: windows-latest
       fail-fast: false
 
     steps:
@@ -79,38 +79,37 @@ jobs:
 
       - name: "Test 1: default case"
         run: |
-          scripts/test.sh foo ""
-        # Intentional fail
+          scripts/test.sh foo "" "*.css"
 
-      - name: "Test 2: localsConvention, first position"
-        if: success() || failure()
-        run: |
-          scripts/test.sh casing/casing "" "--localsConvention camelCaseOnly *.css" casing/camelCaseOnly
-
-      - name: "Test 3: localsConvention, second position"
-        if: success() || failure()
-        run: |
-          scripts/test.sh casing/casing "" "*.css --localsConvention camelCaseOnly" casing/camelCaseOnly
-
-      - name: "Test 4: relative outdir"
-        if: success() || failure()
-        run: |
-          scripts/test.sh foo "" "--outdir generated *.css" "" generated/
-
-      - name: "Test 5: absolute outdir"
-        if: success() || failure()
-        run: |
-          scripts/test.sh foo "" "-o $GITHUB_WORKSPACE/generated *.css" "" "$GITHUB_WORKSPACE"/generated/
-
-      - name: "Test 6: json file config"
-        if: success() || failure()
-        run: |
-          scripts/test.sh foo csstypedrc.json
-
-      - name: "Test 7: yaml file config"
-        if: success() || failure()
-        run: |
-          scripts/test.sh foo csstypedrc.yaml "" "" generated/
+      #      - name: "Test 2: localsConvention, first position"
+      #        if: success() || failure()
+      #        run: |
+      #          scripts/test.sh casing/casing "" "--localsConvention camelCaseOnly *.css" casing/camelCaseOnly
+      #
+      #      - name: "Test 3: localsConvention, second position"
+      #        if: success() || failure()
+      #        run: |
+      #          scripts/test.sh casing/casing "" "*.css --localsConvention camelCaseOnly" casing/camelCaseOnly
+      #
+      #      - name: "Test 4: relative outdir"
+      #        if: success() || failure()
+      #        run: |
+      #          scripts/test.sh foo "" "--outdir generated *.css" "" generated/
+      #
+      #      - name: "Test 5: absolute outdir"
+      #        if: success() || failure()
+      #        run: |
+      #          scripts/test.sh foo "" "-o $GITHUB_WORKSPACE/generated *.css" "" "$GITHUB_WORKSPACE"/generated/
+      #
+      #      - name: "Test 6: json file config"
+      #        if: success() || failure()
+      #        run: |
+      #          scripts/test.sh foo csstypedrc.json
+      #
+      #      - name: "Test 7: yaml file config"
+      #        if: success() || failure()
+      #        run: |
+      #          scripts/test.sh foo csstypedrc.yaml "" "" generated/
 
       - name: "Test 8: custom config path (and js file config)"
         if: success() || failure()
